[package]
authors = ["rep-nop <repnop@outlook.com>"]
name = "riirogue"
version = "0.1.0"
[dependencies]
ggez = "0.4.2"
pathfinding = "0.8.0"
rand = "0.5.0"

[profile.dev]
opt-level = 3
overflow-checks = false
